### ISSUE TITLE
ggplot objects are not equal due to environments

### ISSUE THREAD

**Issue by joemirizio** [r-lib/waldo#56]
Two identical `ggplot2::ggplot` objects report differences in environment objects when using `waldo`. This is also the case when setting `ignore_function_env` and `ignore_formula_env`. 

These plots pass comparison using `all.equal` and `testthat::compare`.

```r
sample_ggplot <- function () {
  ggplot2::ggplot(data = iris, ggplot2::aes(x = Species)) + ggplot2::geom_bar()
}

a <- sample_ggplot()
b <- sample_ggplot()

all.equal(a, b)
#> [1] TRUE

testthat::compare(a, b)
#> Equal

waldo::compare(a, b)
#> `old$layers[[1]]` is <env:0x7ff89f3e2db0>
#> `new$layers[[1]]` is <env:0x7ff89b945158>
#> 
#> `old$scales` is <env:0x7ff89e6cfe98>
#> `new$scales` is <env:0x7ff89e1ce448>
#> 
#> `attr(old$mapping$x, '.Environment')` is <env:0x7ff89b953ba0>
#> `attr(new$mapping$x, '.Environment')` is <env:0x7ff89f3c52b0>
#> 
#> `old$coordinates` is <env:0x7ff89f847000>
#> `new$coordinates` is <env:0x7ff89e2d3a10>
#> 
#> `old$facet` is <env:0x7ff89e7a1d00>
#> `new$facet` is <env:0x7ff89b9d6d38>
#> 
#> `old$plot_env` is <env:0x7ff89b953ba0>
#> `new$plot_env` is <env:0x7ff89f3c52b0>

waldo::compare(a, b, ignore_function_env = T, ignore_formula_env = T, ignore_attr = T)
#> `old[[2]][[1]]` is <env:0x7ff89f3e2db0>
#> `new[[2]][[1]]` is <env:0x7ff89b945158>
#> 
#> `old[[3]]` is <env:0x7ff89e6cfe98>
#> `new[[3]]` is <env:0x7ff89e1ce448>
#> 
#> `old[[6]]` is <env:0x7ff89f847000>
#> `new[[6]]` is <env:0x7ff89e2d3a10>
#> 
#> `old[[7]]` is <env:0x7ff89e7a1d00>
#> `new[[7]]` is <env:0x7ff89b9d6d38>
#> 
#> `old[[8]]` is <env:0x7ff89b953ba0>
#> `new[[8]]` is <env:0x7ff89f3c52b0>
```
<sup>Created on 2020-11-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
This is correct; the plots are different.

**Comment by pwildenhain** [comment]
What's the best way to test equality with plots using `waldo`? (Or really `testthat` 3rd edition)

**Comment by hadley** [comment]
What's your goal? Generally we use https://vdiffr.r-lib.org

**Comment by joemirizio** [comment]
Gotcha! Some of our tests generate plots and compare them. This passed in `testthat` 2nd edition, but does not work the same way in 3rd edition. I figured since the only diffs were environment-related and #24 seemed to address that, it might be an issue.

We looked into `vdiffr` a while back, but decided the comparison to saved images wasn't what we really wanted. Maybe we'll re-evaluate or switch back to `testthat` 2nd edition

**Comment by jgabry** [comment]
> Generally we use https://vdiffr.r-lib.org

I love vdiffr and use it extensively when comparing a plot to a saved file, but what about something like testing that two different functions produce the same plot? Previously the two resulting ggplot objects could be compared with `expect_equal()` because it didn't fail if the environments were different (although perhaps that wasn't good practice). It doesn't seem like vdiffr will take two ggplot objects as input and compare them and it also doesn't seem possible to compare both to the same saved SVG file unless I missed that. 

In general the testthat 3rd edition seems great!

**Comment by jgabry** [comment]
Here's an example that hopefully gives more context to my previous comment. In the [bayesplot](https://github.com/stan-dev/bayesplot) package we want to test that the two functions `ppc_scatter_avg()` and `ppc_scatter()` create the same plot in the special case where there is only 1 row in the input matrix. We currently have this: 

```r
  expect_equal(ppc_scatter_avg(y, yrep[1,, drop=FALSE]), ppc_scatter(y, yrep[1,, drop = FALSE]))
```

As far as I can tell, `vdiffr::expect_doppelganger()` isn't really designed to handle a case like that because it compares one plot to a single SVG file, but if there's a way to use vdfirr for this I would happily make the switch for this kind of test.

**Comment by hadley** [comment]
@jgabry previously you were comparing some representation of the plot that ignored a bunch of environments that I suspect are actually very important when determining what the plots look like. Your tests only worked by coincidence, not because you were testing the right thing.

**Comment by jgabry** [comment]
> Your tests only worked by coincidence, not because you were testing the right thing.

Yeah you're totally right, but then what is the correct way to test that two functions produce a plot that looks the same if vdiffr can only compare one plot to a saved SVG file? We're just trying to figure out how to do it correctly now that what we were doing before doesn't work anymore (for good reason, as you pointed out). I also realize that this issue is in the waldo repo, so I'm happy to move my follow up question somewhere else more appropriate (e.g. vdiffr), I was just responding here because it wasn't clear to me how to make your recommendation above to use vdiffr work in this case. Anyway, thanks for all the great packages!

**Comment by hadley** [comment]
I'd suggest filing an issue in vdiffr so we can look into filling that gap.

**Comment by jgabry** [comment]
Ok great, will do. Thanks!

**Comment by dannyparsons** [comment]
@jgabry Did you find a way to solve this challenge? I have a similar need to check that the output from a wrapper function produces the same graph as the plain ggplot2 code. Is that your suggestion was deemed out of scope for `vdiffr`. Was there anywhere you found that does something like this? Thanks.
