### ISSUE TITLE
Option to ignore order of named list elements?

### ISSUE THREAD

**Issue by mpettis** [r-lib/waldo#72]
This is working as advertised, per https://github.com/r-lib/waldo/blob/master/README.Rmd#L124-L132 .  I was wondering if it would be feasible to have an option that ignores the order of named elements in a list when comparing for equality?

For the below, could an option be provided that would ignore the order of the names `a` and `b` and return that these two lists are equal?

``` r
waldo::compare(
  list(a=1, b=2),
  list(b=2, a=1))
#> `names(old)`: "a" "b"    
#> `names(new)`:     "b" "a"
```

<sup>Created on 2021-03-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
Yeah, I hit this the other day too. An option seems reasonable to me.

**Comment by mpettis** [comment]
Thank you.  To add, possibly for help, is that there probably have to be some strict constraints like "ignore order only if every element has a name."  I tried this and, compared to above, it now says that values are different too if I throw an unnamed entry into the mix:

``` r
waldo::compare(
    list(a=1, b=2, 3),
    list(b=2, a=1, 3))
#> `names(old)`: "a" "b"     ""
#> `names(new)`:     "b" "a" ""
#> 
#> `old[[1]]`: 1
#> `new[[1]]`: 2
#> 
#> `old[[2]]`: 2
#> `new[[2]]`: 1
```

<sup>Created on 2021-03-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by dmurdoch** [comment]
Rather than setting this as an option in the test, would it be reasonable to set something in the objects being compared to signal that order shouldn't matter?

Here's why I'd prefer that:  A recent update to `rgl` changed the order in which some named components (for `mesh3d` objects) were put in a list.  This caused some reverse dependencies to fail because `testthat::expect_equal()` detected the change.  I was able to fix this by creating a `compare_proxy` method that sorted components alphabetically, but I don't really want `waldo` to be loaded every time `rgl` is loaded, so setting `compare_proxy.mesh3d` as a method is tricky.

On the other hand, if I could set something on my `mesh3d` objects that says they should be treated as unordered, then the `compare_proxy.default` method could see that and not worry about order.

A similar issue arises with a `NULL` list component:  in `rgl` that's treated the same as a missing one, so `compare_proxy.mesh3d` removes it.  In a discussion on the R-package-devel list, there was also a suggestion that some list elements should be treated as private and ignored by `compare()` (perhaps by naming convention, or some explicit declaration).

Is there any interest in this?

**Comment by hadley** [comment]
@dmurdoch oooh I like that idea much better, especially if the attribute used a `waldo_` prefix so it was clear it was specific for waldo.

**Comment by dmurdoch** [comment]
I'll put together a PR.

**Comment by hadley** [comment]
@dmurdoch I should also mention that there are a couple of options if you want to define `compare_proxy.mesh3d` without creating a hard dependency on waldo (i.e. allowing you to put it in suggests, not imports). If you're ok with requiring 3.6 or later, you can use the new `S3method()` namespace directive; if you want to support older versions of R you can copy `vctrs::s3_register()` into your package and call it.
