### ISSUE TITLE
Dates are displayed as numeric

### ISSUE THREAD

**Issue by Bisaloo** [r-lib/waldo#98]
Reprex:

``` r
waldo::compare(as.Date("2021-08-17"), as.Date("2021-08-16"))
#> `old`: 18856
#> `new`: 18855
```

<sup>Created on 2021-08-17 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0.9000)</sup>

I understand this is difficult because dates might be stored as a large variety of formats but the current behaviour makes it difficult to read the output.

I believe a slightly better behaviour would be to display dates in the same format used by `print.Date()`, i.e. "%Y-%m-%d". But you might have a better idea.

**Comment by hadley** [comment]
Hmmmm, maybe I could add special case displays for Date and POSIXt? The challenge is getting the logic 100% correct because there are a bunch of edge cases where dates look the same but are actually different:

``` r
(x1 <- .Date(1))
#> [1] "1970-01-02"
(x2 <- .Date(1.1))
#> [1] "1970-01-02"

waldo::compare(x1, x2)
#> `old`: 1.0
#> `new`: 1.1
```

<sup>Created on 2021-08-17 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>
